logging:
  level: DEBUG
  file: datops_manager/logs/dataops_manager.log
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] - %(message)s"
  handlers:
    console:
      enabled: true
      level: DEBUG
    file:
      enabled: true
      level: INFO
      filename: datops_manager/logs/dataops_manager.log